platform:
  - x86

image:
  - Visual Studio 2019

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - make_win64_msvc.bat
  - cd ..
  - bam\bam.exe config=debug -r sc test
  - bam\bam.exe config=release -r sc test

build: OFF
